### ISSUE TITLE
Application to netcdf files 

### ISSUE THREAD

**Issue by solhailu** [adrHuerta/rainfall_onset#1]
Hi adrHuerta,

Thanks for sharing the Code it's is just great. Do you have a similar script for netcdf files?

Best regards, 

Solomon

**Comment by adrHuerta** [comment]
Hello @solhailu 

Sorry for my (very) late reply.
You can find a "faster" version of the code (and for gridded data) in [adrHuerta/rainfall_onset2](https://github.com/adrHuerta/rainfall_onset2)

I have to say that I did not test with the previous one, but I believe it works fine

Regards
Adrian
